// Initialise the global array that allows the lookup of the depth of a given object
// GM2.0 does not have a depth on objects so on import from 1.x a global array is created
// NOTE: MacroExpansion is used to insert the array initialisation at import time
gml_pragma( "global", "__global_object_depths()");

// insert the generated arrays here
global.__objectDepths[0] = -100; // net_manager
global.__objectDepths[1] = -10; // player
global.__objectDepths[2] = 0; // avatar
global.__objectDepths[3] = 0; // gravatar
global.__objectDepths[4] = 0; // input_manager
global.__objectDepths[5] = 0; // stat_manager
global.__objectDepths[6] = -200; // accolade_manager
global.__objectDepths[7] = -101; // challenge_manager
global.__objectDepths[8] = 0; // character_generic
global.__objectDepths[9] = -100; // xp_bar
global.__objectDepths[10] = -100; // challenge_generic
global.__objectDepths[11] = -103; // popup_drawer
global.__objectDepths[12] = -80; // accolade_generic
global.__objectDepths[13] = 0; // bpart_generic
global.__objectDepths[14] = 1000000000; // background_drawer
global.__objectDepths[15] = 0; // weapon_generic
global.__objectDepths[16] = 0; // bullet_generic
global.__objectDepths[17] = 0; // weapon_drop_generic
global.__objectDepths[18] = 0; // tossable_generic
global.__objectDepths[19] = 0; // flash_generic
global.__objectDepths[20] = -91; // flash_hitscan_simple_generic
global.__objectDepths[21] = 0; // splosion_generic
global.__objectDepths[22] = -84; // die_generic
global.__objectDepths[23] = 0; // two_way_generic
global.__objectDepths[24] = 0; // shootable_generic
global.__objectDepths[25] = -10; // limb_generic
global.__objectDepths[26] = -95; // glare_controller
global.__objectDepths[27] = 0; // spawn_point_generic
global.__objectDepths[28] = 0; // intensity_generic
global.__objectDepths[29] = 0; // col_generic
global.__objectDepths[30] = 0; // ambient_generic
global.__objectDepths[31] = 0; // kLight
global.__objectDepths[32] = -95; // modal_window
global.__objectDepths[33] = 0; // modal_button
global.__objectDepths[34] = -9999; // modal_dialogue
global.__objectDepths[35] = 0; // bn_dialogue
global.__objectDepths[36] = 0; // bn_typical
global.__objectDepths[37] = 0; // modal_splat
global.__objectDepths[38] = 0; // bn_input_field
global.__objectDepths[39] = 0; // bn_meditor
global.__objectDepths[40] = -99; // kill_feed
global.__objectDepths[41] = -100; // chat_feed
global.__objectDepths[42] = -100; // feed_message
global.__objectDepths[43] = -101; // bn_play
global.__objectDepths[44] = 0; // bn_tab
global.__objectDepths[45] = -101; // bn_play_tab
global.__objectDepths[46] = -101; // bn_armory
global.__objectDepths[47] = -101; // bn_challenges
global.__objectDepths[48] = -101; // bn_leaderboards
global.__objectDepths[49] = -101; // bn_stats
global.__objectDepths[50] = -101; // bn_friends
global.__objectDepths[51] = -101; // bn_settings
global.__objectDepths[52] = -101; // bn_logout
global.__objectDepths[53] = -101; // bn_randomize
global.__objectDepths[54] = -101; // bn_postmatch
global.__objectDepths[55] = -101; // bn_postmatch_done
global.__objectDepths[56] = -10; // bn_start_matchmaking
global.__objectDepths[57] = 0; // bn_play_modal
global.__objectDepths[58] = 0; // tab_bg_modal
global.__objectDepths[59] = 0; // bn_leave_matchmaking
global.__objectDepths[60] = 0; // bn_ready
global.__objectDepths[61] = 0; // bn_vote
global.__objectDepths[62] = -101; // bn_create_new
global.__objectDepths[63] = -100; // bn_login_user
global.__objectDepths[64] = -103; // randomize_name
global.__objectDepths[65] = 0; // autoplay_d
global.__objectDepths[66] = 0; // autoplay_a
global.__objectDepths[67] = 0; // autoplay_b
global.__objectDepths[68] = 0; // autoplay_c
global.__objectDepths[69] = -99; // modal_controls
global.__objectDepths[70] = 0; // bn_restore_defaults
global.__objectDepths[71] = 0; // bn_use_keyboard
global.__objectDepths[72] = 0; // bn_use_gamepad
global.__objectDepths[73] = 0; // bn_gen_settings
global.__objectDepths[74] = 0; // bn_match_settings
global.__objectDepths[75] = 0; // bn_control_settings
global.__objectDepths[76] = 0; // bn_logout_settings
global.__objectDepths[77] = 0; // bn_match_quit
global.__objectDepths[78] = 0; // bn_cedit
global.__objectDepths[79] = 0; // bn_clabel
global.__objectDepths[80] = 0; // bn_tbottom
global.__objectDepths[81] = 0; // bn_stat_tab
global.__objectDepths[82] = 0; // bn_slabel
global.__objectDepths[83] = 0; // modal_stat_history
global.__objectDepths[84] = 0; // modal_meter
global.__objectDepths[85] = 0; // modal_table
global.__objectDepths[86] = 0; // toggle_button_generic
global.__objectDepths[87] = 0; // button_generic
global.__objectDepths[88] = -101; // input_field
global.__objectDepths[89] = 0; // weapon_placeholder1
global.__objectDepths[90] = 0; // weapon_frag
global.__objectDepths[91] = 0; // weapon_torque
global.__objectDepths[92] = 0; // weapon_sticky
global.__objectDepths[93] = 0; // weapon_flashbang
global.__objectDepths[94] = 0; // weapon_smoke
global.__objectDepths[95] = 0; // weapon_ink
global.__objectDepths[96] = 0; // weapon_snare
global.__objectDepths[97] = 0; // weapon_flame
global.__objectDepths[98] = 0; // weapon_pistol
global.__objectDepths[99] = 0; // weapon_carbine
global.__objectDepths[100] = 0; // weapon_boltok
global.__objectDepths[101] = 0; // weapon_thumper
global.__objectDepths[102] = 0; // weapon_shotgun
global.__objectDepths[103] = 0; // weapon_double
global.__objectDepths[104] = 0; // weapon_rifle
global.__objectDepths[105] = 0; // weapon_longshot
global.__objectDepths[106] = 0; // weapon_stomper
global.__objectDepths[107] = 0; // weapon_boom
global.__objectDepths[108] = 0; // weapon_rocket
global.__objectDepths[109] = 0; // weapon_smg
global.__objectDepths[110] = 0; // weapon_tickler
global.__objectDepths[111] = 0; // weapon_lmg
global.__objectDepths[112] = 0; // weapon_vulcan
global.__objectDepths[113] = 0; // weapon_placeholder2
global.__objectDepths[114] = -100; // hit_marker
global.__objectDepths[115] = 0; // bullet_shotgun
global.__objectDepths[116] = 0; // bullet_double
global.__objectDepths[117] = 0; // bullet_pistol
global.__objectDepths[118] = 0; // bullet_long
global.__objectDepths[119] = 0; // bullet_stomper
global.__objectDepths[120] = -95; // bullet_rifle
global.__objectDepths[121] = -95; // bullet_smg
global.__objectDepths[122] = -95; // bullet_tickler
global.__objectDepths[123] = -95; // bullet_lmg
global.__objectDepths[124] = -95; // bullet_boltok
global.__objectDepths[125] = -95; // bullet_carbine
global.__objectDepths[126] = -95; // bullet_vulcan
global.__objectDepths[127] = -95; // bullet_boom
global.__objectDepths[128] = -95; // bullet_rocket
global.__objectDepths[129] = 0; // bullet_frag
global.__objectDepths[130] = 0; // bullet_thumper
global.__objectDepths[131] = 0; // bullet_sticky
global.__objectDepths[132] = 0; // bullet_torque
global.__objectDepths[133] = 0; // bullet_flashbang
global.__objectDepths[134] = 0; // bullet_smoke
global.__objectDepths[135] = 0; // bullet_ink
global.__objectDepths[136] = 0; // bullet_flame
global.__objectDepths[137] = 0; // bullet_snare
global.__objectDepths[138] = 0; // flash_hitscan_simple_pistol
global.__objectDepths[139] = 0; // flash_hitscan_simple_long
global.__objectDepths[140] = 0; // flash_hitscan_simple_torque
global.__objectDepths[141] = 0; // flash_hitscan_simple_vulcan
global.__objectDepths[142] = 0; // flash_hitscan_simple_shotgun
global.__objectDepths[143] = 0; // flash_none
global.__objectDepths[144] = 0; // flash_pistol
global.__objectDepths[145] = 0; // flash_smg
global.__objectDepths[146] = 0; // flash_tickler
global.__objectDepths[147] = 0; // flash_rifle
global.__objectDepths[148] = 0; // flash_lmg
global.__objectDepths[149] = 0; // flash_vulcan
global.__objectDepths[150] = 0; // flash_boom
global.__objectDepths[151] = 0; // flash_rocket
global.__objectDepths[152] = 0; // flash_sticky
global.__objectDepths[153] = 0; // flash_torque
global.__objectDepths[154] = 0; // flash_torque_charging
global.__objectDepths[155] = 0; // flash_boom_flying
global.__objectDepths[156] = 0; // flash_shotgun
global.__objectDepths[157] = 0; // flash_double
global.__objectDepths[158] = 0; // flash_torque_launch
global.__objectDepths[159] = 0; // flash_hitscan_pistol
global.__objectDepths[160] = 0; // flash_hitscan_shotgun
global.__objectDepths[161] = 0; // splosion_frag
global.__objectDepths[162] = 0; // splosion_thumper
global.__objectDepths[163] = 0; // splosion_flame_instant
global.__objectDepths[164] = -94; // splosion_flame
global.__objectDepths[165] = 0; // splosion_sticky
global.__objectDepths[166] = 0; // splosion_torque
global.__objectDepths[167] = 0; // splosion_boom
global.__objectDepths[168] = 0; // splosion_rocket
global.__objectDepths[169] = 0; // splosion_flashbang
global.__objectDepths[170] = -94; // splosion_smoke
global.__objectDepths[171] = -94; // splosion_ink
global.__objectDepths[172] = -94; // splosion_snare
global.__objectDepths[173] = 0; // solid_generic
global.__objectDepths[174] = 0; // dynamic_generic
global.__objectDepths[175] = -87; // rag_generic
global.__objectDepths[176] = 0; // rag_head
global.__objectDepths[177] = 0; // rag_torso
global.__objectDepths[178] = 0; // rag_leg
global.__objectDepths[179] = 0; // rag_shin
global.__objectDepths[180] = 0; // rag_hat
global.__objectDepths[181] = 0; // rag_shoulder
global.__objectDepths[182] = 0; // rag_forearm
global.__objectDepths[183] = 0; // rag_foot
global.__objectDepths[184] = 0; // launch_pad
global.__objectDepths[185] = 0; // block
global.__objectDepths[186] = 0; // wedge_right
global.__objectDepths[187] = 0; // wedge_right_mirrored
global.__objectDepths[188] = 0; // flat_right
global.__objectDepths[189] = 0; // flat_right_mirrored
global.__objectDepths[190] = 0; // wedge_left
global.__objectDepths[191] = 0; // wedge_left_mirrored
global.__objectDepths[192] = 0; // flat_left
global.__objectDepths[193] = 0; // flat_left_mirrored
global.__objectDepths[194] = 0; // block2_top
global.__objectDepths[195] = 0; // block2_top_true
global.__objectDepths[196] = 0; // block2
global.__objectDepths[197] = 0; // wedge_right2
global.__objectDepths[198] = 0; // wedge_right2_mirrored
global.__objectDepths[199] = 0; // flat_right2
global.__objectDepths[200] = 0; // flat_right2_mirrored
global.__objectDepths[201] = 0; // wedge_left2
global.__objectDepths[202] = 0; // wedge_left2_mirrored
global.__objectDepths[203] = 0; // flat_left2
global.__objectDepths[204] = 0; // flat_left2_mirrored
global.__objectDepths[205] = 0; // wedge
global.__objectDepths[206] = 0; // wedge2
global.__objectDepths[207] = 0; // weapon_drop_frag
global.__objectDepths[208] = 0; // weapon_drop_tickler
global.__objectDepths[209] = 0; // weapon_drop_thumper
global.__objectDepths[210] = 0; // weapon_drop_flame
global.__objectDepths[211] = 0; // weapon_drop_snare
global.__objectDepths[212] = 0; // weapon_drop_sticky
global.__objectDepths[213] = 0; // weapon_drop_ink
global.__objectDepths[214] = 0; // weapon_drop_flashbang
global.__objectDepths[215] = 0; // weapon_drop_smoke
global.__objectDepths[216] = 0; // weapon_drop_shotgun
global.__objectDepths[217] = 0; // weapon_drop_double
global.__objectDepths[218] = 0; // weapon_drop_lmg
global.__objectDepths[219] = 0; // weapon_drop_long
global.__objectDepths[220] = 0; // weapon_drop_stomper
global.__objectDepths[221] = 0; // weapon_drop_smg
global.__objectDepths[222] = 0; // weapon_drop_vulcan
global.__objectDepths[223] = 0; // weapon_drop_torque
global.__objectDepths[224] = 0; // weapon_drop_boom
global.__objectDepths[225] = 0; // weapon_drop_rocket
global.__objectDepths[226] = 0; // weapon_drop_boltok
global.__objectDepths[227] = 0; // weapon_drop_carbine
global.__objectDepths[228] = 0; // spawn_point_neutral
global.__objectDepths[229] = 0; // spawn_point0
global.__objectDepths[230] = 0; // spawn_point1
global.__objectDepths[231] = -999999999; // cursor
global.__objectDepths[232] = -97; // hit_indicator
global.__objectDepths[233] = 0; // title
global.__objectDepths[234] = 0; // processing
global.__objectDepths[235] = -12; // particle_controller
global.__objectDepths[236] = 1; // fx
global.__objectDepths[237] = 0; // blood_splosion
global.__objectDepths[238] = -80; // blood_particle
global.__objectDepths[239] = -93; // rubble
global.__objectDepths[240] = 0; // spraynspray
global.__objectDepths[241] = -110; // action_word
global.__objectDepths[242] = 0; // fog
global.__objectDepths[243] = 0; // snow
global.__objectDepths[244] = 0; // dust
global.__objectDepths[245] = 0; // purple_haze
global.__objectDepths[246] = 0; // green_haze
global.__objectDepths[247] = -999999999; // cursor_generic
global.__objectDepths[248] = 0; // cursor_placeholder1
global.__objectDepths[249] = 0; // cursor_frag
global.__objectDepths[250] = 0; // cursor_pistol
global.__objectDepths[251] = 0; // cursor_boltok
global.__objectDepths[252] = 0; // cursor_long
global.__objectDepths[253] = 0; // cursor_rifle
global.__objectDepths[254] = 0; // cursor_carbine
global.__objectDepths[255] = 0; // cursor_stomper
global.__objectDepths[256] = 0; // cursor_boom
global.__objectDepths[257] = 0; // cursor_rocket
global.__objectDepths[258] = 0; // cursor_smg
global.__objectDepths[259] = 0; // cursor_tickler
global.__objectDepths[260] = 0; // cursor_torque
global.__objectDepths[261] = 0; // cursor_vulcan
global.__objectDepths[262] = 0; // cursor_lmg
global.__objectDepths[263] = 0; // cursor_shotgun
global.__objectDepths[264] = 0; // cursor_placeholder2
global.__objectDepths[265] = -2; // obj_light_mouse
global.__objectDepths[266] = -2; // obj_light_static
global.__objectDepths[267] = -2; // obj_light_point
global.__objectDepths[268] = -2; // obj_light_spot
global.__objectDepths[269] = -2; // obj_lightsimple
global.__objectDepths[270] = -95; // lighting
global.__objectDepths[271] = 0; // light_generic
global.__objectDepths[272] = 0; // light0
global.__objectDepths[273] = 0; // intensity0
global.__objectDepths[274] = 0; // intensity1
global.__objectDepths[275] = 0; // intensity2
global.__objectDepths[276] = 0; // col0
global.__objectDepths[277] = 0; // col1
global.__objectDepths[278] = 0; // col2
global.__objectDepths[279] = 0; // col3
global.__objectDepths[280] = 0; // col4
global.__objectDepths[281] = 0; // col5
global.__objectDepths[282] = 0; // ambient_normal
global.__objectDepths[283] = 0; // ambient_dark


global.__objectNames[0] = "net_manager";
global.__objectNames[1] = "player";
global.__objectNames[2] = "avatar";
global.__objectNames[3] = "gravatar";
global.__objectNames[4] = "input_manager";
global.__objectNames[5] = "stat_manager";
global.__objectNames[6] = "accolade_manager";
global.__objectNames[7] = "challenge_manager";
global.__objectNames[8] = "character_generic";
global.__objectNames[9] = "xp_bar";
global.__objectNames[10] = "challenge_generic";
global.__objectNames[11] = "popup_drawer";
global.__objectNames[12] = "accolade_generic";
global.__objectNames[13] = "bpart_generic";
global.__objectNames[14] = "background_drawer";
global.__objectNames[15] = "weapon_generic";
global.__objectNames[16] = "bullet_generic";
global.__objectNames[17] = "weapon_drop_generic";
global.__objectNames[18] = "tossable_generic";
global.__objectNames[19] = "flash_generic";
global.__objectNames[20] = "flash_hitscan_simple_generic";
global.__objectNames[21] = "splosion_generic";
global.__objectNames[22] = "die_generic";
global.__objectNames[23] = "two_way_generic";
global.__objectNames[24] = "shootable_generic";
global.__objectNames[25] = "limb_generic";
global.__objectNames[26] = "glare_controller";
global.__objectNames[27] = "spawn_point_generic";
global.__objectNames[28] = "intensity_generic";
global.__objectNames[29] = "col_generic";
global.__objectNames[30] = "ambient_generic";
global.__objectNames[31] = "kLight";
global.__objectNames[32] = "modal_window";
global.__objectNames[33] = "modal_button";
global.__objectNames[34] = "modal_dialogue";
global.__objectNames[35] = "bn_dialogue";
global.__objectNames[36] = "bn_typical";
global.__objectNames[37] = "modal_splat";
global.__objectNames[38] = "bn_input_field";
global.__objectNames[39] = "bn_meditor";
global.__objectNames[40] = "kill_feed";
global.__objectNames[41] = "chat_feed";
global.__objectNames[42] = "feed_message";
global.__objectNames[43] = "bn_play";
global.__objectNames[44] = "bn_tab";
global.__objectNames[45] = "bn_play_tab";
global.__objectNames[46] = "bn_armory";
global.__objectNames[47] = "bn_challenges";
global.__objectNames[48] = "bn_leaderboards";
global.__objectNames[49] = "bn_stats";
global.__objectNames[50] = "bn_friends";
global.__objectNames[51] = "bn_settings";
global.__objectNames[52] = "bn_logout";
global.__objectNames[53] = "bn_randomize";
global.__objectNames[54] = "bn_postmatch";
global.__objectNames[55] = "bn_postmatch_done";
global.__objectNames[56] = "bn_start_matchmaking";
global.__objectNames[57] = "bn_play_modal";
global.__objectNames[58] = "tab_bg_modal";
global.__objectNames[59] = "bn_leave_matchmaking";
global.__objectNames[60] = "bn_ready";
global.__objectNames[61] = "bn_vote";
global.__objectNames[62] = "bn_create_new";
global.__objectNames[63] = "bn_login_user";
global.__objectNames[64] = "randomize_name";
global.__objectNames[65] = "autoplay_d";
global.__objectNames[66] = "autoplay_a";
global.__objectNames[67] = "autoplay_b";
global.__objectNames[68] = "autoplay_c";
global.__objectNames[69] = "modal_controls";
global.__objectNames[70] = "bn_restore_defaults";
global.__objectNames[71] = "bn_use_keyboard";
global.__objectNames[72] = "bn_use_gamepad";
global.__objectNames[73] = "bn_gen_settings";
global.__objectNames[74] = "bn_match_settings";
global.__objectNames[75] = "bn_control_settings";
global.__objectNames[76] = "bn_logout_settings";
global.__objectNames[77] = "bn_match_quit";
global.__objectNames[78] = "bn_cedit";
global.__objectNames[79] = "bn_clabel";
global.__objectNames[80] = "bn_tbottom";
global.__objectNames[81] = "bn_stat_tab";
global.__objectNames[82] = "bn_slabel";
global.__objectNames[83] = "modal_stat_history";
global.__objectNames[84] = "modal_meter";
global.__objectNames[85] = "modal_table";
global.__objectNames[86] = "toggle_button_generic";
global.__objectNames[87] = "button_generic";
global.__objectNames[88] = "input_field";
global.__objectNames[89] = "weapon_placeholder1";
global.__objectNames[90] = "weapon_frag";
global.__objectNames[91] = "weapon_torque";
global.__objectNames[92] = "weapon_sticky";
global.__objectNames[93] = "weapon_flashbang";
global.__objectNames[94] = "weapon_smoke";
global.__objectNames[95] = "weapon_ink";
global.__objectNames[96] = "weapon_snare";
global.__objectNames[97] = "weapon_flame";
global.__objectNames[98] = "weapon_pistol";
global.__objectNames[99] = "weapon_carbine";
global.__objectNames[100] = "weapon_boltok";
global.__objectNames[101] = "weapon_thumper";
global.__objectNames[102] = "weapon_shotgun";
global.__objectNames[103] = "weapon_double";
global.__objectNames[104] = "weapon_rifle";
global.__objectNames[105] = "weapon_longshot";
global.__objectNames[106] = "weapon_stomper";
global.__objectNames[107] = "weapon_boom";
global.__objectNames[108] = "weapon_rocket";
global.__objectNames[109] = "weapon_smg";
global.__objectNames[110] = "weapon_tickler";
global.__objectNames[111] = "weapon_lmg";
global.__objectNames[112] = "weapon_vulcan";
global.__objectNames[113] = "weapon_placeholder2";
global.__objectNames[114] = "hit_marker";
global.__objectNames[115] = "bullet_shotgun";
global.__objectNames[116] = "bullet_double";
global.__objectNames[117] = "bullet_pistol";
global.__objectNames[118] = "bullet_long";
global.__objectNames[119] = "bullet_stomper";
global.__objectNames[120] = "bullet_rifle";
global.__objectNames[121] = "bullet_smg";
global.__objectNames[122] = "bullet_tickler";
global.__objectNames[123] = "bullet_lmg";
global.__objectNames[124] = "bullet_boltok";
global.__objectNames[125] = "bullet_carbine";
global.__objectNames[126] = "bullet_vulcan";
global.__objectNames[127] = "bullet_boom";
global.__objectNames[128] = "bullet_rocket";
global.__objectNames[129] = "bullet_frag";
global.__objectNames[130] = "bullet_thumper";
global.__objectNames[131] = "bullet_sticky";
global.__objectNames[132] = "bullet_torque";
global.__objectNames[133] = "bullet_flashbang";
global.__objectNames[134] = "bullet_smoke";
global.__objectNames[135] = "bullet_ink";
global.__objectNames[136] = "bullet_flame";
global.__objectNames[137] = "bullet_snare";
global.__objectNames[138] = "flash_hitscan_simple_pistol";
global.__objectNames[139] = "flash_hitscan_simple_long";
global.__objectNames[140] = "flash_hitscan_simple_torque";
global.__objectNames[141] = "flash_hitscan_simple_vulcan";
global.__objectNames[142] = "flash_hitscan_simple_shotgun";
global.__objectNames[143] = "flash_none";
global.__objectNames[144] = "flash_pistol";
global.__objectNames[145] = "flash_smg";
global.__objectNames[146] = "flash_tickler";
global.__objectNames[147] = "flash_rifle";
global.__objectNames[148] = "flash_lmg";
global.__objectNames[149] = "flash_vulcan";
global.__objectNames[150] = "flash_boom";
global.__objectNames[151] = "flash_rocket";
global.__objectNames[152] = "flash_sticky";
global.__objectNames[153] = "flash_torque";
global.__objectNames[154] = "flash_torque_charging";
global.__objectNames[155] = "flash_boom_flying";
global.__objectNames[156] = "flash_shotgun";
global.__objectNames[157] = "flash_double";
global.__objectNames[158] = "flash_torque_launch";
global.__objectNames[159] = "flash_hitscan_pistol";
global.__objectNames[160] = "flash_hitscan_shotgun";
global.__objectNames[161] = "splosion_frag";
global.__objectNames[162] = "splosion_thumper";
global.__objectNames[163] = "splosion_flame_instant";
global.__objectNames[164] = "splosion_flame";
global.__objectNames[165] = "splosion_sticky";
global.__objectNames[166] = "splosion_torque";
global.__objectNames[167] = "splosion_boom";
global.__objectNames[168] = "splosion_rocket";
global.__objectNames[169] = "splosion_flashbang";
global.__objectNames[170] = "splosion_smoke";
global.__objectNames[171] = "splosion_ink";
global.__objectNames[172] = "splosion_snare";
global.__objectNames[173] = "solid_generic";
global.__objectNames[174] = "dynamic_generic";
global.__objectNames[175] = "rag_generic";
global.__objectNames[176] = "rag_head";
global.__objectNames[177] = "rag_torso";
global.__objectNames[178] = "rag_leg";
global.__objectNames[179] = "rag_shin";
global.__objectNames[180] = "rag_hat";
global.__objectNames[181] = "rag_shoulder";
global.__objectNames[182] = "rag_forearm";
global.__objectNames[183] = "rag_foot";
global.__objectNames[184] = "launch_pad";
global.__objectNames[185] = "block";
global.__objectNames[186] = "wedge_right";
global.__objectNames[187] = "wedge_right_mirrored";
global.__objectNames[188] = "flat_right";
global.__objectNames[189] = "flat_right_mirrored";
global.__objectNames[190] = "wedge_left";
global.__objectNames[191] = "wedge_left_mirrored";
global.__objectNames[192] = "flat_left";
global.__objectNames[193] = "flat_left_mirrored";
global.__objectNames[194] = "block2_top";
global.__objectNames[195] = "block2_top_true";
global.__objectNames[196] = "block2";
global.__objectNames[197] = "wedge_right2";
global.__objectNames[198] = "wedge_right2_mirrored";
global.__objectNames[199] = "flat_right2";
global.__objectNames[200] = "flat_right2_mirrored";
global.__objectNames[201] = "wedge_left2";
global.__objectNames[202] = "wedge_left2_mirrored";
global.__objectNames[203] = "flat_left2";
global.__objectNames[204] = "flat_left2_mirrored";
global.__objectNames[205] = "wedge";
global.__objectNames[206] = "wedge2";
global.__objectNames[207] = "weapon_drop_frag";
global.__objectNames[208] = "weapon_drop_tickler";
global.__objectNames[209] = "weapon_drop_thumper";
global.__objectNames[210] = "weapon_drop_flame";
global.__objectNames[211] = "weapon_drop_snare";
global.__objectNames[212] = "weapon_drop_sticky";
global.__objectNames[213] = "weapon_drop_ink";
global.__objectNames[214] = "weapon_drop_flashbang";
global.__objectNames[215] = "weapon_drop_smoke";
global.__objectNames[216] = "weapon_drop_shotgun";
global.__objectNames[217] = "weapon_drop_double";
global.__objectNames[218] = "weapon_drop_lmg";
global.__objectNames[219] = "weapon_drop_long";
global.__objectNames[220] = "weapon_drop_stomper";
global.__objectNames[221] = "weapon_drop_smg";
global.__objectNames[222] = "weapon_drop_vulcan";
global.__objectNames[223] = "weapon_drop_torque";
global.__objectNames[224] = "weapon_drop_boom";
global.__objectNames[225] = "weapon_drop_rocket";
global.__objectNames[226] = "weapon_drop_boltok";
global.__objectNames[227] = "weapon_drop_carbine";
global.__objectNames[228] = "spawn_point_neutral";
global.__objectNames[229] = "spawn_point0";
global.__objectNames[230] = "spawn_point1";
global.__objectNames[231] = "cursor";
global.__objectNames[232] = "hit_indicator";
global.__objectNames[233] = "title";
global.__objectNames[234] = "processing";
global.__objectNames[235] = "particle_controller";
global.__objectNames[236] = "fx";
global.__objectNames[237] = "blood_splosion";
global.__objectNames[238] = "blood_particle";
global.__objectNames[239] = "rubble";
global.__objectNames[240] = "spraynspray";
global.__objectNames[241] = "action_word";
global.__objectNames[242] = "fog";
global.__objectNames[243] = "snow";
global.__objectNames[244] = "dust";
global.__objectNames[245] = "purple_haze";
global.__objectNames[246] = "green_haze";
global.__objectNames[247] = "cursor_generic";
global.__objectNames[248] = "cursor_placeholder1";
global.__objectNames[249] = "cursor_frag";
global.__objectNames[250] = "cursor_pistol";
global.__objectNames[251] = "cursor_boltok";
global.__objectNames[252] = "cursor_long";
global.__objectNames[253] = "cursor_rifle";
global.__objectNames[254] = "cursor_carbine";
global.__objectNames[255] = "cursor_stomper";
global.__objectNames[256] = "cursor_boom";
global.__objectNames[257] = "cursor_rocket";
global.__objectNames[258] = "cursor_smg";
global.__objectNames[259] = "cursor_tickler";
global.__objectNames[260] = "cursor_torque";
global.__objectNames[261] = "cursor_vulcan";
global.__objectNames[262] = "cursor_lmg";
global.__objectNames[263] = "cursor_shotgun";
global.__objectNames[264] = "cursor_placeholder2";
global.__objectNames[265] = "obj_light_mouse";
global.__objectNames[266] = "obj_light_static";
global.__objectNames[267] = "obj_light_point";
global.__objectNames[268] = "obj_light_spot";
global.__objectNames[269] = "obj_lightsimple";
global.__objectNames[270] = "lighting";
global.__objectNames[271] = "light_generic";
global.__objectNames[272] = "light0";
global.__objectNames[273] = "intensity0";
global.__objectNames[274] = "intensity1";
global.__objectNames[275] = "intensity2";
global.__objectNames[276] = "col0";
global.__objectNames[277] = "col1";
global.__objectNames[278] = "col2";
global.__objectNames[279] = "col3";
global.__objectNames[280] = "col4";
global.__objectNames[281] = "col5";
global.__objectNames[282] = "ambient_normal";
global.__objectNames[283] = "ambient_dark";


// create another array that has the correct entries
var len = array_length_1d(global.__objectDepths);
global.__objectID2Depth = [];
for( var i=0; i<len; ++i ) {
	var objID = asset_get_index( global.__objectNames[i] );
	if (objID >= 0) {
		global.__objectID2Depth[ objID ] = global.__objectDepths[i];
	} // end if
} // end for