"C:\Program Files\7-Zip\7z.exe" e "C:\Users\Kyle\Games\Griefer\Applications\Griefer 2.0.zip" -y -o"C:\Users\Kyle\Games\Griefer\Applications\Griefer 2.0"
xcopy /s/e /y "C:\Users\Kyle\Games\Griefer\Applications\Griefer 2.0\*" "C:\Users\Kyle\Puddlesquid\downloads\Griefer 2.0\"
set /p DUMMY=Press Enter to Close...