global.wspawn_default = 30*30
global.vulcan = "Vulcan"
global.pistol = "Derringer"
global.rifle = "Spitfire"
global.shotgun = "Mincer"
global.frag = "Frag"
global.flashbang = "Flashbang"
global.smoke = "Smoke"
global.lmg = "Heavy Barrel"
global.smg = "Cicada"
global.longshot = "Lobotomizer"
global.boom = "Mortar"
global.boltok = "Hand Cannon"
global.ink = "Poison"
global.sticky = "Sticky"
global.torque = "Twerk Bow"
global.rocket = "The Son-Of-A"
global.stomper = "Stomper"
global.double = "Double Barrel"
global.flame = "Incendiary"
global.snare = "Snare"
global.carbine = "Carbine"
global.tickler = "Tickler"
global.thumper = "Thumper"

global.vulcan_pose = "rifle"
global.pistol_pose = "pistol"
global.rifle_pose = "rifle"
global.nade_pose = "nade"
global.shotgun_pose = "rifle"
global.longshot_pose = "rifle"
global.smg_pose = "pistol"
global.lmg_pose = "rifle"
global.boom_pose = "rifle"
global.boltok_pose = "pistol"
global.torque_pose = "rifle"
global.rocket_pose = "rifle"
global.stomper_pose = "rifle"
global.double_pose = "rifle"
global.carbine_pose = "rifle"
global.tickler_pose = "pistol"
global.thumper_pose = "pistol"

global.vulcan_scale = 1.3
global.pistol_scale = 1.15
global.rifle_scale = 1.1
global.nade_scale = 1.5
global.shotgun_scale = 1.125
global.longshot_scale = 0.85
global.smg_scale = 1.1
global.lmg_scale = 1.1
global.boom_scale = 1.25
global.boltok_scale = 1
global.ink_scale = 1.75
global.sticky_scale = 1.6
global.torque_scale = 0.9
global.rocket_scale = 1.15
global.stomper_scale = 1.125
global.double_scale = 1.05
global.flame_scale = 1.5
global.snare_scale = 1.5
global.carbine_scale = 1.25
global.tickler_scale = 1.1
global.thumper_scale = 0.9

global.torque_col = make_color_rgb(100,255,100);
