    pkgCreate()
        if nth_frame(1) obj_update_real(myPlayer(),"rot_true",0)
        if nth_frame(1) obj_update_real(myPlayer(),"sprite_index",0)
        if nth_frame(1) obj_update_real(myPlayer(),"myX",0)
        if nth_frame(1) obj_update_real(myPlayer(),"myY",0)
        if nth_frame(4) obj_update_string(myPlayer(),"animation",0)
        
        if nth_frame(15) obj_update_real(myPlayer(),"match_points",0)
        if nth_frame(16) obj_update_real(myPlayer(),"match_deaths",0)
        if nth_frame(17) obj_update_real(myPlayer(),"match_kills",0)
        if nth_frame(18) obj_update_real(myPlayer(),"match_assists",0)
        
        if nth_frame(30) obj_update_real(myPlayer(),"visible",0)
        if nth_frame(11) obj_update_real(myPlayer(),"animation_speed",0)
        if nth_frame(12) obj_update_real(myPlayer(),"animation_direction",0)
        if nth_frame(13) obj_update_real(myPlayer(),"animation_xscale",0)
        if nth_frame(14) obj_update_real(myPlayer(),"animation_index",0)
        if nth_frame(10) obj_update_real(myPlayer(),"active_weapon_sprite",0)
        if nth_frame(10) obj_update_real(myPlayer(),"arms_posing",0)
        if nth_frame(10) obj_update_string(myPlayer(),"arm_pose",0)
        if nth_frame(15) obj_update_real(myPlayer(),"arm_animation_length",0)
        if nth_frame(16) obj_update_real(myPlayer(),"arm_animation_index",0)
        if nth_frame(17) obj_update_real(myPlayer(),"arm_animation_direction",0)
        if nth_frame(18) obj_update_real(myPlayer(),"arm_animation_speed",0)
        if nth_frame(20) obj_update_real(myPlayer(),"active_weapon_prescaler",0)
    pkgSend()
