    pkgCreate()
        //obj_update_real(net_manager.local_player,"image_alpha",0)
        //obj_update_real(net_manager.local_player,"image_blend",0)
        if nth_frame(room_speed) obj_update_real(net_manager.local_player,"visible",0)
        obj_update_real(net_manager.local_player,"sprite_index",0)
        if nth_frame(4) obj_update_string(net_manager.local_player,"animation",0)
        if nth_frame(11) obj_update_real(net_manager.local_player,"animation_speed",0)
        if nth_frame(12) obj_update_real(net_manager.local_player,"animation_direction",0)
        if nth_frame(13) obj_update_real(net_manager.local_player,"animation_xscale",0)
        if nth_frame(14) obj_update_real(net_manager.local_player,"animation_index",0)
        if nth_frame(10) obj_update_real(net_manager.local_player,"active_weapon_sprite",0)
        if nth_frame(1) obj_update_real(net_manager.local_player,"rot_true",0)
        if nth_frame(10) obj_update_real(net_manager.local_player,"arms_posing",0)
        if nth_frame(10) obj_update_string(net_manager.local_player,"arm_pose",0)
        if nth_frame(15) obj_update_real(net_manager.local_player,"arm_animation_length",0)
        if nth_frame(16) obj_update_real(net_manager.local_player,"arm_animation_index",0)
        if nth_frame(17) obj_update_real(net_manager.local_player,"arm_animation_direction",0)
        if nth_frame(18) {
            printf("updating arm_animation_speed: "+string(objVarRead(net_manager.local_player,"arm_animation_speed")))
            obj_update_real(net_manager.local_player,"arm_animation_speed",0)
        }
        if nth_frame(20) obj_update_real(net_manager.local_player,"active_weapon_prescaler",0)
        //obj_update_real(net_manager.local_player,"arm_y_extra",0)
        //obj_update_real(net_manager.local_player,"arm_rot_extra",0)
        //if nth_frame(20) obj_update_real(net_manager.local_player,"kick",0)
        obj_update_real(net_manager.local_player,"myX",0)
        obj_update_real(net_manager.local_player,"myY",0)
    pkgSend()