#macro GARBAGE -52.1234
#macro WVIEW 640
#macro HVIEW 480
#macro NO_HANDLE -69
#macro BAD_READ -99.1234
#macro WARNINGS 1
#macro C_CROUCH 3
#macro C_DROP 16
#macro C_EVADE 4
#macro C_GRENADES 15
#macro C_JUMP 2
#macro C_LOOK_SENS 18
#macro C_MOUSE_SENS 17
#macro C_MOVE_LEFT 0
#macro C_MOVE_RIGHT 1
#macro C_NEXT 6
#macro C_PICKUP 8
#macro C_PREV 5
#macro C_PRIMARY 12
#macro C_QUICKTOSS 11
#macro C_RELOAD 9
#macro C_SECONDARY 13
#macro C_SHOOT 10
#macro C_SIDEARM_QUICK 7
#macro C_SIDEARM 14
#macro C_SWAP_STICKS 19
