/// @description initialize
input_string = "kyle"
instantClear = false
input_active = false
label = "Username"
alarm[0] = 30/3
blink = false
max_length = 20
str_cursor = ""
backspace_counter = 0
backspace_hold_delay = 60
backspace_delay = backspace_hold_delay
tab_delay = 0
auto_started = false
text_linesep = 16
alpha = 1
font = fnt_button
master_scale = 1

